//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 04:42:42 PM EDT 
//


package org.plasma.xml.xslt;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.w3.org/1999/XSL/Transform}anyType">
 *       &lt;attribute name="stylesheet-prefix" use="required" type="{http://www.w3.org/1999/XSL/Transform}prefix" />
 *       &lt;attribute name="result-prefix" use="required" type="{http://www.w3.org/1999/XSL/Transform}prefix" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
public class NamespaceAlias
    extends AnyType
{

    @XmlAttribute(name = "stylesheet-prefix", required = true)
    protected String stylesheetPrefix;
    @XmlAttribute(name = "result-prefix", required = true)
    protected String resultPrefix;

    /**
     * Gets the value of the stylesheetPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStylesheetPrefix() {
        return stylesheetPrefix;
    }

    /**
     * Sets the value of the stylesheetPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStylesheetPrefix(String value) {
        this.stylesheetPrefix = value;
    }

    /**
     * Gets the value of the resultPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultPrefix() {
        return resultPrefix;
    }

    /**
     * Sets the value of the resultPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultPrefix(String value) {
        this.resultPrefix = value;
    }

}
