//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 04:42:42 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.w3.org/1999/XSL/Transform", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.plasma.xml.xslt;
