//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.29 at 09:12:29 AM MST 
//


package org.plasma.query.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JoinType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="JoinType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="inner"/>
 *     &lt;enumeration value="left_outer"/>
 *     &lt;enumeration value="right_outer"/>
 *     &lt;enumeration value="cross"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "JoinType")
@XmlEnum
public enum JoinType {

    @XmlEnumValue("inner")
    INNER("inner"),
    @XmlEnumValue("left_outer")
    LEFT___OUTER("left_outer"),
    @XmlEnumValue("right_outer")
    RIGHT___OUTER("right_outer"),
    @XmlEnumValue("cross")
    CROSS("cross");
    private final String value;

    JoinType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static JoinType fromValue(String v) {
        for (JoinType c: JoinType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
