//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.12 at 12:34:50 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.servicelabs.org/plasma/query", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.plasma.query.model;
