package org.plasma.provisioning;

public interface ProvisioningConstants {
    
	public static String PROVISIONING_NAMESPACE_URI = "http://www.servicelabs.org/plasma/provisioning";
	
    public final static String TEMPLATE_PARAM_NAME_PACKAGE_CONFIG = "cfg";
    public final static String TEMPLATE_PARAM_NAME_TARGET_DIRECTORY = "dir";
    public final static String TEMPLATE_PARAM_NAME_TARGET_BASE_DIRECTORY = "basedir";
    public final static String TEMPLATE_PARAM_NAME_AUTHOR = "author";
    public final static String TEMPLATE_PARAM_NAME_VERSION = "version";
 
    public final static String TEMPLATE_PARAM_VALUE_AUTHOR = "Generated by Plasma Provisioning Tools";
    public final static String TEMPLATE_PARAM_VALUE_VERSION = "0.7.24";
    
}
