/**
 *         PlasmaSDO™ License
 * 
 * This is a community release of PlasmaSDO™, a dual-license 
 * Service Data Object (SDO) 2.1 implementation. 
 * This particular copy of the software is released under the 
 * version 2 of the GNU General Public License. PlasmaSDO™ was developed by 
 * TerraMeta Software, Inc.
 * 
 * Copyright (c) 2013, TerraMeta Software, Inc. All rights reserved.
 * 
 * General License information can be found below.
 * 
 * This distribution may include materials developed by third
 * parties. For license and attribution notices for these
 * materials, please refer to the documentation that accompanies
 * this distribution (see the "Licenses for Third-Party Components"
 * appendix) or view the online documentation at 
 * <http://plasma-sdo.org/licenses/>.
 *  
 */
package org.plasma.provisioning;

public interface ProvisioningConstants {
    
	public static String PROVISIONING_NAMESPACE_URI = "http://www.servicelabs.org/plasma/provisioning";
	
    public final static String TEMPLATE_PARAM_NAME_PACKAGE_CONFIG = "cfg";
    public final static String TEMPLATE_PARAM_NAME_TARGET_DIRECTORY = "dir";
    public final static String TEMPLATE_PARAM_NAME_TARGET_BASE_DIRECTORY = "basedir";
    public final static String TEMPLATE_PARAM_NAME_AUTHOR = "author";
    public final static String TEMPLATE_PARAM_NAME_VERSION = "version";
 
    public final static String TEMPLATE_PARAM_VALUE_AUTHOR = "Generated by Plasma Provisioning Tools";
    public final static String TEMPLATE_PARAM_VALUE_VERSION = "0.7.24";
    
}
