/**
 * Copyright 2017 TerraMeta Software, Inc.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.plasma.provisioning;

public interface ProvisioningConstants {

  public static String PROVISIONING_NAMESPACE_URI = "http://www.terrameta.org/plasma/metamodel";

  public final static String TEMPLATE_PARAM_NAME_PACKAGE_CONFIG = "cfg";
  public final static String TEMPLATE_PARAM_NAME_TARGET_DIRECTORY = "dir";
  public final static String TEMPLATE_PARAM_NAME_TARGET_BASE_DIRECTORY = "basedir";
  public final static String TEMPLATE_PARAM_NAME_AUTHOR = "author";
  public final static String TEMPLATE_PARAM_NAME_VERSION = "version";

  public final static String TEMPLATE_PARAM_VALUE_AUTHOR = "Generated by Plasma Provisioning Tools";
  public final static String TEMPLATE_PARAM_VALUE_VERSION = "0.7.24";

}
